[package]
name = "ethereum-tx-sign"
version = "1.0.0"
description = "Allows you to model a raw ethereum transaction and sign it with your private key"
repository = "https://github.com/synlestidae/ethereum-tx-sign"
license = "MIT"
keywords = ["web3", "ethereum", "transaction", "sign"]
authors = ["Mate Antunovic <mateATantunovic.nz>"]
readme = "README.md"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tiny-keccak="2.0.2"
secp256k1 = { version= "0.17.2", features=["recovery"] }
rlp = "0.4.5"
ethereum-types = "0.9.0"
hex = "0.4.2"